# Token Configuration for BSC Market Maker Bot

# Major tokens on BSC
tokens:
  - address: "0x2170Ed0880ac9A755fd29B2688956BD959F933F8"
    symbol: "ETH"
    name: "Ethereum Token"
    decimals: 18
    whitelisted: true
    blacklisted: false
    category: "major"
    min_liquidity_bnb: 100

  - address: "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d"
    symbol: "USDC"
    name: "USD Coin"
    decimals: 18
    whitelisted: true
    blacklisted: false
    category: "stablecoin"
    min_liquidity_bnb: 50

  - address: "0x55d398326f99059fF775485246999027B3197955"
    symbol: "USDT"
    name: "Tether USD"
    decimals: 18
    whitelisted: true
    blacklisted: false
    category: "stablecoin"
    min_liquidity_bnb: 50

  - address: "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56"
    symbol: "BUSD"
    name: "BUSD Token"
    decimals: 18
    whitelisted: true
    blacklisted: false
    category: "stablecoin"
    min_liquidity_bnb: 50

  - address: "0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c"
    symbol: "BTCB"
    name: "BTCB Token"
    decimals: 18
    whitelisted: true
    blacklisted: false
    category: "major"
    min_liquidity_bnb: 100

  - address: "0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82"
    symbol: "CAKE"
    name: "PancakeSwap Token"
    decimals: 18
    whitelisted: true
    blacklisted: false
    category: "defi"
    min_liquidity_bnb: 20

  - address: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
    symbol: "WBNB"
    name: "Wrapped BNB"
    decimals: 18
    whitelisted: true
    blacklisted: false
    category: "native"
    min_liquidity_bnb: 0

# Risk categories
risk_levels:
  low:
    - "stablecoin"
    - "major"
  medium:
    - "defi"
    - "gaming"
  high:
    - "meme"
    - "new"

# Blacklisted tokens (known scams/rug pulls)
blacklist:
  - "0x0000000000000000000000000000000000000000"  # Example blacklisted address

# Trading pairs restrictions
restricted_pairs:
  - base: "USDT"
    quote: "USDC"
    reason: "Low volatility, not suitable for market making"