'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'en' | 'ja' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译字典
const translations = {
  zh: {
    // 导航
    'nav.dashboard': '仪表板',
    'nav.wallets': '钱包管理',
    'nav.settings': '设置',
    'nav.trading': '交易',
    'nav.monitoring': '监控',
    
    // 仪表板
    'dashboard.title': 'BSC Trading Bot Dashboard',
    'dashboard.subtitle': 'Welcome to your trading control center',
    'dashboard.apiStatus': 'API状态',
    'dashboard.tradingPerformance': '交易表现',
    'dashboard.walletBalance': '钱包余额',
    'dashboard.successRate': '成功率',
    'dashboard.systemStatus': '系统状态',
    'dashboard.liveMetrics': '实时指标',
    'dashboard.refresh': '刷新',
    'dashboard.connected': '已连接',
    'dashboard.disconnected': '已断开',
    'dashboard.loading': '加载中...',
    'dashboard.tradeSuccessRate': '交易成功率',
    'dashboard.overallStatus': '整体状态',
    'dashboard.systemUptime': '系统运行时间',
    'dashboard.apiResponseTime': 'API响应时间',
    'dashboard.memoryUsage': '内存使用率',
    'dashboard.activeConnections': '活跃连接',
    'dashboard.websocket': 'WebSocket',
    'dashboard.active': '活跃',
    'dashboard.inactive': '非活跃',
    'dashboard.wallets': '个钱包',
    'dashboard.trades': '笔交易',
    
    // 交易页面
    'trading.title': '交易界面',
    'trading.subtitle': '执行单笔交易或批量操作',
    'trading.singleTrade': '单笔交易',
    'trading.batchTrading': '批量交易',
    'trading.advancedBatch': '高级批量',
    'trading.tradeHistory': '交易历史',
    'trading.tradeConfiguration': '交易配置',
    'trading.quoteAnalysis': '报价和分析',
    'trading.buy': '买入',
    'trading.sell': '卖出',
    'trading.tokenIn': '输入代币',
    'trading.tokenOut': '输出代币',
    'trading.amount': '数量',
    'trading.slippageTolerance': '滑点容忍度 (%)',
    'trading.walletAddress': '钱包地址 (可选)',
    'trading.selectWalletGroup': '或选择钱包组',
    'trading.getQuote': '获取报价',
    'trading.addToBatch': '添加到批量',
    'trading.executeTrade': '执行交易',
    'trading.batchConfiguration': '批量配置',
    'trading.batchOverview': '批量概览',
    'trading.executionStrategy': '执行策略',
    'trading.parallel': '并行 - 同时执行所有',
    'trading.sequential': '顺序 - 逐个执行',
    'trading.staggered': '交错 - 带延迟',
    'trading.maxConcurrentTrades': '最大并发交易数',
    'trading.delayBetweenTrades': '交易间延迟 (毫秒)',
    'trading.previewBatch': '预览批量',
    'trading.executeBatch': '执行批量',
    'trading.totalTrades': '总交易数',
    'trading.strategy': '策略',
    'trading.buyOrders': '买单',
    'trading.sellOrders': '卖单',
    'trading.recentTrades': '最近交易',
    'trading.remove': '移除',
    'trading.addTradesToBatch': '添加交易以创建批量',
    'trading.clickGetQuote': '点击"获取报价"查看交易分析',
    'trading.youPay': '您支付:',
    'trading.youReceive': '您接收:',
    'trading.price': '价格:',
    'trading.priceImpact': '价格影响:',
    'trading.recommendedSlippage': '推荐滑点:',
    'trading.minimumReceived': '最少接收:',
    'trading.gasEstimate': 'Gas估算:',
    'trading.totalCost': '总成本:',
    'trading.type': '类型',
    'trading.token': '代币',
    'trading.status': '状态',
    'trading.pnl': '盈亏',
    'trading.time': '时间',
    'trading.actions': '操作',
    'trading.view': '查看',
    'trading.batchTradePreview': '批量交易预览',
    'trading.configuration': '配置',
    'trading.from': '从',
    'trading.to': '到',
    'trading.slippage': '滑点',
    'trading.close': '关闭',
    
    // 监控页面
    'monitoring.title': '系统监控',
    'monitoring.subtitle': '实时系统健康和性能指标',
    'monitoring.refresh': '刷新',
    'monitoring.activeAlerts': '活跃警报',
    'monitoring.systemHealth': '系统健康',
    'monitoring.avgResponseTime': 'API响应时间',
    'monitoring.requestsPerSec': '每秒请求数',
    'monitoring.critical': '严重',
    'monitoring.healthy': '健康',
    'monitoring.lastMinuteAverage': '最后一分钟平均',
    'monitoring.currentLoad': '当前负载',
    'monitoring.alerts': '警报',
    'monitoring.metrics': '指标',
    'monitoring.healthChecks': '健康检查',
    'monitoring.activeAlertsTable': '活跃警报',
    'monitoring.severity': '严重程度',
    'monitoring.component': '组件',
    'monitoring.message': '消息',
    'monitoring.time': '时间',
    'monitoring.count': '计数',
    'monitoring.actions': '操作',
    'monitoring.acknowledge': '确认',
    'monitoring.acknowledged': '已确认',
    'monitoring.noActiveAlerts': '无活跃警报',
    'monitoring.systemResourceUsage': '系统资源使用情况',
    'monitoring.responseTime': '响应时间',
    'monitoring.currentSystemStatus': '当前系统状态',
    'monitoring.cpuUsage': 'CPU使用率',
    'monitoring.memoryUsage': '内存使用率',
    'monitoring.activeConnections': '活跃连接',
    'monitoring.componentHealthChecks': '组件健康检查',
    
    // 钱包页面
    'wallets.title': '钱包管理',
    'wallets.subtitle': '管理和创建交易钱包',
    'wallets.totalWallets': '总钱包数',
    'wallets.totalBalance': '总余额',
    'wallets.walletGroups': '钱包组数',
    'wallets.activeWallets': '有余额钱包',
    'wallets.walletList': '钱包列表',
    'wallets.address': '地址',
    'wallets.label': '标签',
    'wallets.group': '组',
    'wallets.balance': '余额',
    'wallets.tier': '层级',
    'wallets.createdAt': '创建时间',
    'wallets.actions': '操作',
    'wallets.createSingle': '创建单个钱包',
    'wallets.createBatch': '批量创建',
    'wallets.export': '导出钱包',
    'wallets.batchCreateTitle': '批量创建钱包',
    'wallets.createCount': '创建数量',
    'wallets.maxWalletsHint': '最多可创建50个钱包',
    'wallets.groupName': '钱包组名',
    'wallets.groupNamePlaceholder': '输入钱包组名 (可选)',
    'wallets.notice': '注意事项',
    'wallets.batchNotice1': '批量创建的钱包将自动生成新的私钥',
    'wallets.batchNotice2': '请确保妥善保存私钥信息',
    'wallets.batchNotice3': '创建后可以通过导出功能备份钱包数据',
    'wallets.createWallets': '创建 {count} 个钱包',
    
    // 设置页面
    'settings.title': '系统设置',
    'settings.subtitle': '配置系统偏好和安全选项',
    'settings.appearance': '外观设置',
    'settings.darkMode': '深色模式',
    'settings.darkModeDesc': '切换到深色主题',
    'settings.language': '语言设置',
    'settings.selectLanguage': '选择语言',
    'settings.security': '安全设置',
    'settings.apiKey': 'API 密钥',
    'settings.autoSave': '自动保存',
    'settings.autoSaveDesc': '自动保存交易设置',
    'settings.notifications': '通知设置',
    'settings.pushNotifications': '推送通知',
    'settings.pushNotificationsDesc': '接收交易和系统通知',
    'settings.notificationTypes': '通知类型',
    'settings.tradeComplete': '交易完成',
    'settings.priceAlert': '价格预警',
    'settings.systemError': '系统错误',
    'settings.dataManagement': '数据管理',
    'settings.exportData': '导出数据',
    'settings.clearCache': '清除缓存',
    'settings.resetSettings': '重置设置',
    'settings.save': '保存设置',
    
    // 通用
    'common.loading': '加载中...',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.details': '详情',
    'common.success': '成功',
    'common.error': '错误',
    'common.warning': '警告',
    'common.info': '信息',
    'common.show': '显示',
    'common.hide': '隐藏',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.wallets': 'Wallets',
    'nav.settings': 'Settings',
    'nav.trading': 'Trading',
    'nav.monitoring': 'Monitoring',
    
    // Dashboard
    'dashboard.title': 'BSC Trading Bot Dashboard',
    'dashboard.subtitle': 'Welcome to your trading control center',
    'dashboard.apiStatus': 'API Status',
    'dashboard.tradingPerformance': 'Trading Performance',
    'dashboard.walletBalance': 'Wallet Balance',
    'dashboard.successRate': 'Success Rate',
    'dashboard.systemStatus': 'System Status',
    'dashboard.liveMetrics': 'Live Metrics',
    'dashboard.refresh': 'Refresh',
    'dashboard.connected': 'Connected',
    'dashboard.disconnected': 'Disconnected',
    'dashboard.loading': 'Loading...',
    'dashboard.tradeSuccessRate': 'Trade success rate',
    'dashboard.overallStatus': 'Overall Status',
    'dashboard.systemUptime': 'System Uptime',
    'dashboard.apiResponseTime': 'API Response Time',
    'dashboard.memoryUsage': 'Memory Usage',
    'dashboard.activeConnections': 'Active Connections',
    'dashboard.websocket': 'WebSocket',
    'dashboard.active': 'Active',
    'dashboard.inactive': 'Inactive',
    'dashboard.wallets': 'wallets',
    'dashboard.trades': 'trades',
    
    // Trading page
    'trading.title': 'Trading Interface',
    'trading.subtitle': 'Execute single trades or batch operations',
    'trading.singleTrade': 'Single Trade',
    'trading.batchTrading': 'Batch Trading',
    'trading.advancedBatch': 'Advanced Batch',
    'trading.tradeHistory': 'Trade History',
    'trading.tradeConfiguration': 'Trade Configuration',
    'trading.quoteAnalysis': 'Quote & Analysis',
    'trading.buy': 'Buy',
    'trading.sell': 'Sell',
    'trading.tokenIn': 'Token In',
    'trading.tokenOut': 'Token Out',
    'trading.amount': 'Amount',
    'trading.slippageTolerance': 'Slippage Tolerance (%)',
    'trading.walletAddress': 'Wallet Address (optional)',
    'trading.selectWalletGroup': 'Or select wallet group',
    'trading.getQuote': 'Get Quote',
    'trading.addToBatch': 'Add to Batch',
    'trading.executeTrade': 'Execute Trade',
    'trading.batchConfiguration': 'Batch Configuration',
    'trading.batchOverview': 'Batch Overview',
    'trading.executionStrategy': 'Execution Strategy',
    'trading.parallel': 'Parallel - Execute all at once',
    'trading.sequential': 'Sequential - One after another',
    'trading.staggered': 'Staggered - With delays',
    'trading.maxConcurrentTrades': 'Max Concurrent Trades',
    'trading.delayBetweenTrades': 'Delay Between Trades (ms)',
    'trading.previewBatch': 'Preview Batch',
    'trading.executeBatch': 'Execute Batch',
    'trading.totalTrades': 'Total Trades',
    'trading.strategy': 'Strategy',
    'trading.buyOrders': 'Buy Orders',
    'trading.sellOrders': 'Sell Orders',
    'trading.recentTrades': 'Recent Trades',
    'trading.remove': 'Remove',
    'trading.addTradesToBatch': 'Add trades to create a batch',
    'trading.clickGetQuote': 'Click "Get Quote" to see trade analysis',
    'trading.youPay': 'You pay:',
    'trading.youReceive': 'You receive:',
    'trading.price': 'Price:',
    'trading.priceImpact': 'Price Impact:',
    'trading.recommendedSlippage': 'Recommended Slippage:',
    'trading.minimumReceived': 'Minimum Received:',
    'trading.gasEstimate': 'Gas Estimate:',
    'trading.totalCost': 'Total Cost:',
    'trading.type': 'TYPE',
    'trading.token': 'TOKEN',
    'trading.status': 'STATUS',
    'trading.pnl': 'P&L',
    'trading.time': 'TIME',
    'trading.actions': 'ACTIONS',
    'trading.view': 'View',
    'trading.batchTradePreview': 'Batch Trade Preview',
    'trading.configuration': 'Configuration',
    'trading.from': 'FROM',
    'trading.to': 'TO',
    'trading.slippage': 'SLIPPAGE',
    'trading.close': 'Close',
    
    // Monitoring page
    'monitoring.title': 'System Monitoring',
    'monitoring.subtitle': 'Real-time system health and performance metrics',
    'monitoring.refresh': 'Refresh',
    'monitoring.activeAlerts': 'Active Alerts',
    'monitoring.systemHealth': 'System Health',
    'monitoring.avgResponseTime': 'Avg Response Time',
    'monitoring.requestsPerSec': 'Requests/sec',
    'monitoring.critical': 'critical',
    'monitoring.healthy': 'healthy',
    'monitoring.lastMinuteAverage': 'Last minute average',
    'monitoring.currentLoad': 'Current load',
    'monitoring.alerts': 'Alerts',
    'monitoring.metrics': 'Metrics',
    'monitoring.healthChecks': 'Health Checks',
    'monitoring.activeAlertsTable': 'Active Alerts',
    'monitoring.severity': 'SEVERITY',
    'monitoring.component': 'COMPONENT',
    'monitoring.message': 'MESSAGE',
    'monitoring.time': 'TIME',
    'monitoring.count': 'COUNT',
    'monitoring.actions': 'ACTIONS',
    'monitoring.acknowledge': 'Acknowledge',
    'monitoring.acknowledged': 'Acknowledged',
    'monitoring.noActiveAlerts': 'No active alerts',
    'monitoring.systemResourceUsage': 'System Resource Usage',
    'monitoring.responseTime': 'Response Time',
    'monitoring.currentSystemStatus': 'Current System Status',
    'monitoring.cpuUsage': 'CPU Usage',
    'monitoring.memoryUsage': 'Memory Usage',
    'monitoring.activeConnections': 'Active Connections',
    'monitoring.componentHealthChecks': 'Component Health Checks',
    
    // Wallets page
    'wallets.title': 'Wallet Management',
    'wallets.subtitle': 'Manage and create trading wallets',
    'wallets.totalWallets': 'Total Wallets',
    'wallets.totalBalance': 'Total Balance',
    'wallets.walletGroups': 'Wallet Groups',
    'wallets.activeWallets': 'Active Wallets',
    'wallets.walletList': 'Wallet List',
    'wallets.address': 'Address',
    'wallets.label': 'Label',
    'wallets.group': 'Group',
    'wallets.balance': 'Balance',
    'wallets.tier': 'Tier',
    'wallets.createdAt': 'Created At',
    'wallets.actions': 'Actions',
    'wallets.createSingle': 'Create Single Wallet',
    'wallets.createBatch': 'Batch Create',
    'wallets.export': 'Export Wallets',
    'wallets.batchCreateTitle': 'Batch Create Wallets',
    'wallets.createCount': 'Create Count',
    'wallets.maxWalletsHint': 'Maximum 50 wallets can be created',
    'wallets.groupName': 'Wallet Group Name',
    'wallets.groupNamePlaceholder': 'Enter wallet group name (optional)',
    'wallets.notice': 'Notice',
    'wallets.batchNotice1': 'Batch created wallets will automatically generate new private keys',
    'wallets.batchNotice2': 'Please ensure to save private key information securely',
    'wallets.batchNotice3': 'You can backup wallet data through export function after creation',
    'wallets.createWallets': 'Create {count} Wallets',
    
    // Settings page
    'settings.title': 'System Settings',
    'settings.subtitle': 'Configure system preferences and security options',
    'settings.appearance': 'Appearance Settings',
    'settings.darkMode': 'Dark Mode',
    'settings.darkModeDesc': 'Switch to dark theme',
    'settings.language': 'Language Settings',
    'settings.selectLanguage': 'Select Language',
    'settings.security': 'Security Settings',
    'settings.apiKey': 'API Key',
    'settings.autoSave': 'Auto Save',
    'settings.autoSaveDesc': 'Automatically save trading settings',
    'settings.notifications': 'Notification Settings',
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotificationsDesc': 'Receive trading and system notifications',
    'settings.notificationTypes': 'Notification Types',
    'settings.tradeComplete': 'Trade Complete',
    'settings.priceAlert': 'Price Alert',
    'settings.systemError': 'System Error',
    'settings.dataManagement': 'Data Management',
    'settings.exportData': 'Export Data',
    'settings.clearCache': 'Clear Cache',
    'settings.resetSettings': 'Reset Settings',
    'settings.save': 'Save Settings',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.details': 'Details',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.show': 'Show',
    'common.hide': 'Hide',
  },
  ja: {
    // Navigation
    'nav.dashboard': 'ダッシュボード',
    'nav.wallets': 'ウォレット',
    'nav.settings': '設定',
    'nav.trading': 'トレーディング',
    'nav.monitoring': 'モニタリング',
    
    // Dashboard
    'dashboard.title': 'BSC Trading Bot ダッシュボード',
    'dashboard.subtitle': 'トレーディングコントロールセンターへようこそ',
    'dashboard.apiStatus': 'APIステータス',
    'dashboard.tradingPerformance': 'トレーディングパフォーマンス',
    'dashboard.walletBalance': 'ウォレット残高',
    'dashboard.successRate': '成功率',
    'dashboard.systemStatus': 'システムステータス',
    'dashboard.liveMetrics': 'ライブメトリクス',
    
    // Settings page
    'settings.title': 'システム設定',
    'settings.subtitle': 'システム設定とセキュリティオプションを構成',
    'settings.appearance': '外観設定',
    'settings.darkMode': 'ダークモード',
    'settings.darkModeDesc': 'ダークテーマに切り替え',
    'settings.language': '言語設定',
    'settings.selectLanguage': '言語を選択',
    'settings.security': 'セキュリティ設定',
    'settings.save': '設定を保存',
  },
  ko: {
    // Navigation
    'nav.dashboard': '대시보드',
    'nav.wallets': '지갑',
    'nav.settings': '설정',
    'nav.trading': '거래',
    'nav.monitoring': '모니터링',
    
    // Dashboard
    'dashboard.title': 'BSC Trading Bot 대시보드',
    'dashboard.subtitle': '거래 제어 센터에 오신 것을 환영합니다',
    'dashboard.apiStatus': 'API 상태',
    'dashboard.tradingPerformance': '거래 성과',
    'dashboard.walletBalance': '지갑 잔액',
    'dashboard.successRate': '성공률',
    'dashboard.systemStatus': '시스템 상태',
    'dashboard.liveMetrics': '실시간 지표',
    
    // Settings page
    'settings.title': '시스템 설정',
    'settings.subtitle': '시스템 환경설정 및 보안 옵션 구성',
    'settings.appearance': '외관 설정',
    'settings.darkMode': '다크 모드',
    'settings.darkModeDesc': '다크 테마로 전환',
    'settings.language': '언어 설정',
    'settings.selectLanguage': '언어 선택',
    'settings.security': '보안 설정',
    'settings.save': '설정 저장',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('zh');

  useEffect(() => {
    // Get language from localStorage on mount
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}